name: local
variables:
  - name: port
    value: "3000"
  - name: baseUrl
    value: http://localhost:{{port}}
  - name: token
    value: ""
  - name: userId
    value: "001"
  - name: threadId
    value: ""
  - name: username
    value: ""
  - name: email
    value: johndoe@example.com
  - name: password
    value: password123
